### ISSUE TITLE
Drawing mulitple bounding boxes on a single frame fails

### ISSUE THREAD

**Issue by hohonuuli** [mbari-media-management/cthulhu#2]
MBARI's video lab has reported that when the video is paused, attempts to draw mulitple bounding boxes on a single frame fails. The first box is drawn but subsequent ones are lost.

**Comment by carueda** [comment]
Just to note that I'm not seeing this misbehavior, not at least with my basic setup, which involves a dev environment with a recent clone, running via `./gradlew -t run` and using the video indicated elsewhere (`V3136_20071206T211301Z_16-20-58-06TC_h264.mp4`).

But maybe I'm just not exactly doing the necessary steps to reproduce.

![image](https://user-images.githubusercontent.com/556505/109250212-1d987180-779e-11eb-9e55-e3f6256b17b1.png)

**Comment by hohonuuli** [comment]
@carueda We may need to write an external app for you to quickly reproduce this. Localizations are being passed through zeromq to an internal collection in Cthulhu. Inside cthulhu, there's a SharktoodaIO class that has a controller that maintains a list of collections in sync with an external app. When the annotations are added from the external app, they don't seem to be propagated through to Cthulhu's internal representation. Video of this bug in action at https://youtu.be/BdpkUAuUNfY

**Comment by hohonuuli** [comment]
@carueda Yep. I do not see this when cthulhu is running standalone. Only when connected to VARS. It may be the network comms OR maybe when a bounding box is removed and re-added to the collection use by the comms, that change isn't being propagated through cthulhu's internal data representation.

**Comment by carueda** [comment]
@hohonuuli Seems like a `remove` request is being made (by VARS itself(?)) right after the addition of the box:

This is what I've done:

- on VARS, paused the video
- on Cthulhu, drew a box, which in this test immediately disappeared
- looking at Cthulhu's log:

```
..AnnotationController   | added=[Localization{concept='Concept', elapsedTime=PT1.906S, localizationUuid=44f8ed16-282e-4f32-9c1d-fa3b49820879}]

13:37:11.805 .. o.m.v.sharktopoda.client.localization.IO | Publishing to 'localization':
{"action":"add","localizations":[{"concept":"Concept","elapsedTimeMillis":1906,"durationMillis":0,"videoReferenceUuid":"df8a3eea-7790-4d7d-8892-135a2dbe0eda","localizationUuid":"44f8ed16-282e-4f32-9c1d-fa3b49820879","x":403,"y":771,"width":302,"height":179}]}

13:37:11.806 .. o.m.v.sharktopoda.client.localization.IO | Received on 'localization': {"action":"remove","localizations":[{"concept":"Concept","elapsedTimeMillis":1906,"durationMillis":0,"videoReferenceUuid":"df8a3eea-7790-4d7d-8892-135a2dbe0eda","localizationUuid":"44f8ed16-282e-4f32-9c1d-fa3b49820879","x":403,"y":771,"width":302,"height":179}]}
...
```

So, per the sharktopoda lines above, there was a publish related with `action: add` at 13:37:11.805, but then, an instant later,  a received request with `action: remove`.  This looks suspicious.

Then I just experimented with simply ignoring the subsequent action in `AnnotationManager.remove` and repeated the exercise: now all drawn boxes seem to be retained: 

https://youtu.be/OMo1uBjF0Pc

In that video I captured about 10 pause-and-draw-a-few-boxes runs.  All boxes in all ~10 frames seem to be retained.  In all cases (except ~2) with the boxes being displayed while being drawn and retained upon mouse release, and only in ~2 cases with the boxes not retained upon releasing the mouse. However, all boxes in all frames displayed afterwards (eg upon a replay).

So, two main outcomes/things to investigate further:

- is it possible that VARS (or sharktopoda?) is somehow triggering a subsequent request for removal of the box that was just added?  Possibly because of some timing issue/discrepancy...

- the occasional box disappearing right upon releasing the mouse seems like an unrelated issue, possibly only within Cthulhu itself

Thoughts?

**Comment by hohonuuli** [comment]
Hi Carlos,

> is it possible that VARS (or sharktopoda?) is somehow triggering a subsequent request for removal of the box that was just added? Possibly because of some timing issue/discrepancy...

I have to look at the code to be sure, but yes, VARS removes then re-adds the annotations for a good reason. The sequence is actually

1. Draw box in Cthulhu
2. VARS receives bounding box
3. VARS commits the annotation info to a database via a web service. 
4. The web service returns a modified annotation/localization (e.g. integrates it with existing annotation info and updates various UUIDs on the annotation)
5. VARS removes the original localization from Cthulhu as it is now stale and has out of date data.
6. VARS adds the modified localization back into Cthulhu.

**Comment by carueda** [comment]
(Thanks again @hohonuuli  for your adjustments on the VARS side.)

Just to summarize our findings today:

It seems we are only seeing this issue when using a small time window size (~100ms), which suggests some sort of misalignment (or rounding issue) w.r.t current elapsed time in the video, even when paused. With a bigger window, e.g. 400ms, --selected to be greater than the highest frequency at which the media player reports its time (which is not less than 250ms per previous experiments)-- we were not able to reproduce this issue. 

However, I will do some more investigation to see whether there's some way to still be able to handle small time windows.
